Fix vulnerable dependency issue
Update the requirements.txt to ensure the latest secure version of pyyaml is used. 

ERROR: frontmatter 3.0.5 has requirement PyYAML==3.13, but you'll have pyyaml 5.1 which is incompatible.